// Writes PHOTO-NAMES.md: what to call each student's photo in the Cloudinary
// "profiles" folder.   npm run photos:names
import fs from "node:fs";

const slugify = (name) =>
  name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const source = fs.readFileSync("data/studentsData.ts", "utf8").replace(/\r\n/g, "\n");
const parts = source.split(/\n  "([^"]+)": \{\n/).slice(1);
const rows = [];
for (let i = 0; i < parts.length; i += 2) {
  const name = parts[i];
  rows.push({ name, slug: slugify(name) });
}
rows.sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" }));

const lines = [
  "# Photo names",
  "",
  "Upload each graduate's photos to the Cloudinary folder **`profiles`** and name the files like this (no extension in the name):",
  "",
  "- **`<name>`** is the main photo shown on the profile and in the directory.",
  "- **`<name>_2`**, **`<name>_3`** ... are the gallery photos, in that order.",
  "",
  "The site picks new photos up within about 2 minutes. Re-uploading the same name replaces the photo.",
  "",
  "| Graduate | Main photo name | Gallery names |",
  "|---|---|---|",
  ...rows.map((r) => `| ${r.name} | \`${r.slug}\` | \`${r.slug}_2\`, \`${r.slug}_3\` |`),
  "",
  "_Generated by `npm run photos:names`. Run it again after adding students._",
  "",
];
fs.writeFileSync("PHOTO-NAMES.md", lines.join("\n"));
console.log(`PHOTO-NAMES.md written (${rows.length} graduates).`);
